import type { Metadata, Viewport } from "next"
import { Playfair_Display, Inter } from "next/font/google"
import "./globals.css"
import { LocaleProvider } from "@/lib/locale-context"
import { CookieBanner } from "@/components/cookie-banner"
import { ServiceWorkerRegister } from "@/components/pwa/service-worker-register"
import { InstallPrompt } from "@/components/pwa/install-prompt"
import { buildRestaurantJsonLd } from "@/lib/json-ld"
import { SITE_URL } from "@/lib/site"

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair",
})

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Le Bellagio – Restaurant français à Alès",
  description:
    "Restaurant Le Bellagio à Alès. Cuisine française fait maison, pizzas, à emporter. 23 place Henri Barbusse, 30100 Alès. Réservation : +33 4 66 52 99 59.",
  keywords: [
    "restaurant alès",
    "le bellagio",
    "cuisine française",
    "pizza alès",
    "restaurant gard",
  ],
  applicationName: "lebellagio",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "lebellagio",
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  manifest: "/site.webmanifest",
  openGraph: {
    title: "Le Bellagio – Restaurant français à Alès",
    description: "Cuisine française, fait maison, au cœur d'Alès.",
    type: "website",
    locale: "fr_FR",
    url: SITE_URL,
    siteName: "Le Bellagio",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Le Bellagio – Restaurant français à Alès",
        type: "image/jpeg",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Le Bellagio – Restaurant français à Alès",
    description: "Cuisine française, fait maison, au cœur d'Alès.",
    images: ["/og-image.jpg"],
  },
}

export const viewport: Viewport = {
  themeColor: "#8B1E2D",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
}

// iOS ignores the manifest for its launch splash screen, so it needs an
// explicit `apple-touch-startup-image` per viewport/DPR combo. Images live in
// public/splash/ and are (re)generated by scripts/generate-pwa-assets.mjs
// from public/logo.svg.
const APPLE_SPLASH_SCREENS = [
  { file: "splash-750x1334.png", width: 375, height: 667, dpr: 2 },
  { file: "splash-1242x2208.png", width: 414, height: 736, dpr: 3 },
  { file: "splash-1125x2436.png", width: 375, height: 812, dpr: 3 },
  { file: "splash-828x1792.png", width: 414, height: 896, dpr: 2 },
  { file: "splash-1242x2688.png", width: 414, height: 896, dpr: 3 },
  { file: "splash-1170x2532.png", width: 390, height: 844, dpr: 3 },
  { file: "splash-1284x2778.png", width: 428, height: 926, dpr: 3 },
  { file: "splash-1179x2556.png", width: 393, height: 852, dpr: 3 },
  { file: "splash-1290x2796.png", width: 430, height: 932, dpr: 3 },
  { file: "splash-1536x2048.png", width: 768, height: 1024, dpr: 2 },
  { file: "splash-1668x2388.png", width: 834, height: 1194, dpr: 2 },
  { file: "splash-2048x2732.png", width: 1024, height: 1366, dpr: 2 },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const restaurantJsonLd = buildRestaurantJsonLd()

  return (
    <html lang="fr" className={`${playfair.variable} ${inter.variable} bg-background`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(restaurantJsonLd) }}
        />
        {APPLE_SPLASH_SCREENS.map(({ file, width, height, dpr }) => (
          <link
            key={file}
            rel="apple-touch-startup-image"
            href={`/splash/${file}`}
            media={`(device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`}
          />
        ))}
      </head>
      <body className="font-sans antialiased">
        <LocaleProvider>
          {children}
          <CookieBanner />
          <InstallPrompt />
          <ServiceWorkerRegister />
        </LocaleProvider>
      </body>
    </html>
  )
}
